### ISSUE TITLE
Undefined behavior if static multiXd LatticeObjects are used

### ISSUE THREAD

**Issue by bglaessle** [usqcd-software/qdpxx#23]
Static variables (like the staggered phases in chroma: `lib/util/gauge/stag_phases_s.cc`)
```c++
static multiXd<LatticeABC> abc;
```
cause undefined behavior if they have size>0 when the program exits.

This is due to the fact that the order of initialization (and therefore deconstruction) of the qdp++ allocator map (the_alignment_map) and the empty multiXd is undefined. Maybe worse is that the qdp allocator hooks `atexit`, whereas the multiXd, which **requires the allocator**, is definitely destroyed after that.

Generally one should either prevent static variables that use the qdp++ allocator
or maybe make the_alignment_map a member of the allocator.

*this was moved from* https://github.com/JeffersonLab/chroma/issues/21

**Comment by bjoo** [comment]
I am guessing this may be because the QDP allocator is a singleton, created with the Create Using New policy. I think we can do a create static policy. Then the lifetime may be the same as the other static objects? But there is still an ordering issue potentially?

**Comment by bjoo** [comment]
Hi Ben, I implemented your suggestions with devel 4de4668 . I made the alignment maps part of the allocators themselves. I also changed the Lifetime policies of the Allocator singletons to be NoDestroy (which someone changed to actually destroy during atexit, to avoid memory leaks). I changed the creation policies of the singletons to be CreateStatic. With this fix, the Staggered regression tests in Chroma that used to bomb on exit due to this issue now pass (as long as you don't use the wrong compiler -- see other isssues/NEWS file).
